name: Artifacts
on:
  workflow_dispatch:

jobs:
  artifact-producer:
    name: Produce artifact
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world" > a.txt
          echo "gac" >> a.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
          with:
            name: myfile
            path: a.txt
