name: Passing Variables Between jobs
on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-latest
    outputs:
      foo: ${{ steps.generate-foo.outputs.foo}}
    steps:
      - id: generate-foo
        run: |
          foo=bar
          echo "${foo}"
          echo "x=${foo}" >> "$GITHUB_ENV"
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
      - run: echo "${x}"
    
  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - run: echo ${{ needs.producer.outputs.foo }}
      - run: echo ${x:-<UNSET>}